# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

target 'DummyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DummyApp
  pod 'Alamofire'
  pod 'FutureKit'
  pod 'AlamofireImage'
  target 'DummyAppTests' do
    inherit! :search_paths
  end

end
